#!/usr/bin/env ruby

require_relative 'command_line/command_line_arguments.rb'
require_relative "topologygenerator.rb"
require 'colorize'

begin
    my_command_line_arguments = CommandLineArguments.new
    my_command_line_arguments.run

    topo_gen = Topologygenerator.new({
            "source" => my_command_line_arguments.source,
            "directory_concrete_builders" => my_command_line_arguments.directory_concrete_builders,
            "output_directory" => my_command_line_arguments.output_directory,
            "uri_resource" => my_command_line_arguments.uri_resource
        })
    topo_gen.generate
rescue Exception => ex
  puts "#{ex.class}".red 
  puts "#{ex.message}".blue
end
